# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdas <- function(X, y, al, lam, methodn, tau, mu, weight, MaxIt, Xty, x0, d0, Aoo, Goo) {
    .Call('_PDAS_pdas', PACKAGE = 'PDAS', X, y, al, lam, methodn, tau, mu, weight, MaxIt, Xty, x0, d0, Aoo, Goo)
}

pdas_path <- function(X, y, method, sel, al, tau, mu, del, weight, MaxIt, Lmax, Lmin, N) {
    .Call('_PDAS_pdas_path', PACKAGE = 'PDAS', X, y, method, sel, al, tau, mu, del, weight, MaxIt, Lmax, Lmin, N)
}

pdas_geno <- function(stringname, method, sel, al, tau, mu, del, weight, MaxIt, Lmax, Lmin, Nstep) {
    .Call('_PDAS_pdas_geno', PACKAGE = 'PDAS', stringname, method, sel, al, tau, mu, del, weight, MaxIt, Lmax, Lmin, Nstep)
}

